//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopApi.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EspanolCR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EspanolCR() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopApi.Idioma.EspanolCR", typeof(EspanolCR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó exitosamente..
        /// </summary>
        public static string actualizo_exitoso_generico {
            get {
                return ResourceManager.GetString("actualizo_exitoso_generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La autoridad no se encuentra registrada..
        /// </summary>
        public static string autoridad_sin_registrar {
            get {
                return ResourceManager.GetString("autoridad_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código no se encuentra registrado..
        /// </summary>
        public static string codigo_sin_registrar {
            get {
                return ResourceManager.GetString("codigo_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña inválida..
        /// </summary>
        public static string contrasena_invalida {
            get {
                return ResourceManager.GetString("contrasena_invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ya se encuentra registrado.
        /// </summary>
        public static string correo_existe {
            get {
                return ResourceManager.GetString("correo_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cupón no se encuentra registrado..
        /// </summary>
        public static string cupon_sin_registrar {
            get {
                return ResourceManager.GetString("cupon_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó exitosamente..
        /// </summary>
        public static string elimino_exitoso_generico {
            get {
                return ResourceManager.GetString("elimino_exitoso_generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error interno. Intenté nuevamente..
        /// </summary>
        public static string error_generico {
            get {
                return ResourceManager.GetString("error_generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se registró exitosamente..
        /// </summary>
        public static string registro_exitoso_generico {
            get {
                return ResourceManager.GetString("registro_exitoso_generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiquete no está registrado..
        /// </summary>
        public static string ticket_sin_registrar {
            get {
                return ResourceManager.GetString("ticket_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se editó la categoría..
        /// </summary>
        public static string tienda_categoria_editar {
            get {
                return ResourceManager.GetString("tienda_categoria_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría fue eliminada..
        /// </summary>
        public static string tienda_categoria_eliminar {
            get {
                return ResourceManager.GetString("tienda_categoria_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se registró la categoría..
        /// </summary>
        public static string tienda_categoria_registrar {
            get {
                return ResourceManager.GetString("tienda_categoria_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría no se encuentra registrada..
        /// </summary>
        public static string tienda_categoria_sin_registrar {
            get {
                return ResourceManager.GetString("tienda_categoria_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tienda no está registrada..
        /// </summary>
        public static string tienda_sin_registrar {
            get {
                return ResourceManager.GetString("tienda_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoridad.
        /// </summary>
        public static string titulo_autoridad {
            get {
                return ResourceManager.GetString("titulo_autoridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string titulo_codigo {
            get {
                return ResourceManager.GetString("titulo_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cupón.
        /// </summary>
        public static string titulo_cupon {
            get {
                return ResourceManager.GetString("titulo_cupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string titulo_error {
            get {
                return ResourceManager.GetString("titulo_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiquete.
        /// </summary>
        public static string titulo_ticket {
            get {
                return ResourceManager.GetString("titulo_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienda.
        /// </summary>
        public static string titulo_tienda {
            get {
                return ResourceManager.GetString("titulo_tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría Tienda.
        /// </summary>
        public static string titulo_tienda_categoria {
            get {
                return ResourceManager.GetString("titulo_tienda_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string titulo_usuario {
            get {
                return ResourceManager.GetString("titulo_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string titulo_usuario_ingresar {
            get {
                return ResourceManager.GetString("titulo_usuario_ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue actualizado..
        /// </summary>
        public static string usuario_actualizado {
            get {
                return ResourceManager.GetString("usuario_actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue eliminado..
        /// </summary>
        public static string usuario_eliminado {
            get {
                return ResourceManager.GetString("usuario_eliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} no está  activada..
        /// </summary>
        public static string usuario_inactivo {
            get {
                return ResourceManager.GetString("usuario_inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y/o contraseña incorretos..
        /// </summary>
        public static string usuario_no_existe {
            get {
                return ResourceManager.GetString("usuario_no_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado ningún usuario para esta clave de activación.
        /// </summary>
        public static string usuario_no_verificado {
            get {
                return ResourceManager.GetString("usuario_no_verificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue registrado..
        /// </summary>
        public static string usuario_registrado {
            get {
                return ResourceManager.GetString("usuario_registrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no se encuentra registrado..
        /// </summary>
        public static string usuario_sin_registrar {
            get {
                return ResourceManager.GetString("usuario_sin_registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario activado..
        /// </summary>
        public static string usuario_verificado {
            get {
                return ResourceManager.GetString("usuario_verificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya se encuentra registrado..
        /// </summary>
        public static string validar_usuario_registrado {
            get {
                return ResourceManager.GetString("validar_usuario_registrado", resourceCulture);
            }
        }
    }
}
